--- #YAML:1.0
name:               Net-Rest-Generic
version:            0.11
abstract:           A tool for generically interacting with restfull (or restlike) APIs.
author:
    - Sebastian Green-Husted,Shane Utt <ricecake@tfm.nu>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    LWP::UserAgent:  1
    Test::Deep:      1
    Test::More:      1
    URI:             1
    Want:            1
requires:
    perl:  5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
