---
abstract: 'A tool for generically interacting with restfull (or restlike) APIs.'
author:
  - 'Sebastian Green-Husted,Shane Utt <ricecake@tfm.nu>'
build_requires:
  Test::Deep: 1
  Test::More: 1
  Want: 1
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Rest-Generic
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
version: 0.10
